#!/bin/bash
case $1 in
:) [ "$TCE" ] && x Image-Exiftool 
   shift; exiftool -*duration* $@ ;;
*) ffprobe -v error                       \
   -show_entries format=duration          \
   -of default=noprint_wrappers=1:nokey=1 \
   "$1" ;;
esac
