#!/bin/sh
[ $1 ] || {
  [ "`mem S`" -gt 0 ] && swp=\+
  printf '%s' `
  free -g|head -n2|tail -n1|awk '{printf "%s/%s",$2-$4,$2}'`$swp
  exit; }
[ $1 = : ] && free -g|head -n2|tail -n1|awk '{printf "%s",$2-$4,$2}'
[ $1 = s ] && free -g|tail -n1|awk '{printf "%s",$3}'
[ $1 = S ] && free   |tail -n1|awk '{printf "%s",$3}'
