#!/bin/bash
[ $1 ] || exit
shopt -s lastpipe
[ "$1" = a ] && cli='@ana'
[ "$1" = g ] && cli='@geo'
[ "$1" = e ] && cli='@eli'
[ "$1" = j ] && cli='@jua'
fd acesso $mkt/cli/$cli|xx cat|fzf|read a eml pwd c
echo $eml|xi; read -p pwds && echo $pwd|xi
