#!/bin/bash

url="rtmp://a.rtmp.youtube.com/live2"
key=
#key=hx86-2rxv-6x8u-gwam-b2ca #elisandra

[ $1 ] || ffmpeg \
  -f alsa -ac 2 -i hw:1,0                  \
  -f x11grab -framerate 30 -i ':0.0+0.0'   \
  -c:v libx264 -preset veryfast -b:v 1984k \
  -maxrate 1984k -bufsize 3968k            \
  -vf "format=yuv420p" -g 60               \
  -c:a aac -b:a 128k -ar 44100             \
  -f flv ${url}/${key}

[ $1 ] && ffmpeg \
  -thread_queue_size 1024                  \
  -f alsa -ac 2 -i hw:1,0                  \
  -framerate 30 -i /dev/video0             \
  -c:v libx264 -preset veryfast -b:v 1984k \
  -maxrate 1984k -bufsize 3968k -vf        \
  "scale=1920x1080[v1];[v1]format=yuv420p" \
  -g 60 -c:a aac -b:a 128k -ar 44100       \
  -f flv ${url}/${key}
