#!/bin/bash
# https://web.archive.org/web/20160616013356/https://felixmilea.com/2014/12/running-bash-commands-background-properly/

[ -t 1 ] && exec 1>/dev/null
[ -t 2 ] && exec 2>/dev/null
eval exec $@ &
